services:
  vpn:
    # Ports used: 53, 80, 81, 443
    container_name: vpn
    image: tailscale/tailscale:latest
    hostname: odin
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    healthcheck:
      test: ["CMD-SHELL", "tailscale status --self"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  proxy:
    # Ports used: see `vpn` service
    container_name: proxy
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
    network_mode: service:vpn
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    depends_on:
      vpn:
        condition: service_healthy

  dns:
    # Ports used: 53, 3000
    container_name: dns
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - ./dns/work:/opt/adguardhome/work
      - ./dns/conf:/opt/adguardhome/conf
    # DNS server will not work until the initial setup is finished
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 53 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      # The UI is exposed through the proxy service, but since the
      # proxy service also depends on this service hostname to be
      # resolvable, I cannot add a circular dependency.
      vpn:
        condition: service_healthy

  dashboard:
    # Ports used: 3000
    container_name: dashboard
    image: hywax/mafl
    restart: unless-stopped
    volumes:
      - ./dashboard:/app/data
    depends_on:
      proxy:
        condition: service_healthy

  bookmarks:
    # Ports used: 8080
    container_name: bookmarks
    image: ghcr.io/go-shiori/shiori
    restart: unless-stopped
    environment:
      - SHIORI_DIR=/srv/shiori
      - SHIORI_HTTP_SECRET_KEY=${BOOKMARKS_HTTP_SECRET_KEY}
    volumes:
      - ./bookmarks/shiori:/srv/shiori
    depends_on:
      proxy:
        condition: service_healthy

  # pdf:
  #   # Ports used: 8080
  #   container_name: pdf
  #   image: bentopdf/bentopdf-simple:latest
  #   restart: unless-stopped
  #   labels:
  #     glance.name: PDF tools
  #     glance.icon: sh:bentopdf-light
  #     glance.url: ${PDF_PANEL_URL}
  #     glance.description: Edit PDFs
  #     glance.hide: false
  #   depends_on:
  #     proxy:
  #       condition: service_healthy
